DROP TABLE IF EXISTS TBL_USUARIO;
CREATE TABLE TBL_USUARIO(
    ID INT AUTO_INCREMENT PRIMARY KEY,    
    NOMBRE VARCHAR (50) NOT NULL,
    USUARIO VARCHAR (50) NOT NULL,
    CORREO VARCHAR (50) NOT NULL,
    CLAVE VARCHAR (100) NOT NULL,
    TELEFONO VARCHAR (50) NOT NULL,
    ESTADO CHAR (1) NOT NULL,
    CODIGO_CIUDAD VARCHAR (10) NULL,
    CODIGO_PAIS VARCHAR (10)  NULL,	
	FECHA_CREACION Date not null,
    FECHA_ULTIMA_ACTUALIZACION date not null,
    FECHA_ULTIMO_INGRESO  date NOT NULL
	

);

INSERT INTO TBL_USUARIO(ID, NOMBRE, USUARIO, CORREO, CLAVE, TELEFONO, ESTADO, CODIGO_CIUDAD, CODIGO_PAIS, FECHA_CREACION, FECHA_ULTIMA_ACTUALIZACION, FECHA_ULTIMO_INGRESO )
VALUES
 (1, 'APOLINAR', 'asolis', 'apolina@gmail.com', '$2a$10$bAueeLHkjtYCRu.gEL4/luQcVb9IDgTx0eMZxeDBGtHQnoHDSYWKC', '31541874', '1', '57', '56', '2024-05-30',  '2024-05-30',  '2024-05-30');


